Section A — Exception Handling
1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input

In [1]:
def safe_divide(a,b):
    try:
        result=a/b
        print(result)
    except ZeroDivisionError:
        print("cannot be divide by zero")
    except TypeError :
        print("enter valid number")
    finally:
        print("Operation attempted")

In [4]:
safe_divide(5,0)

cannot be divide by zero
Operation attempted

2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.

In [23]:
class InvalidAgeerror(Exception):
    pass
def validate_age(age):
    if age < 0 or age >120:
        return InvalidAgeerror
    print(f"valid age{age}")

test=[25,30,40]
for i in test:
    try:
        validate_age(i)
    except InvalidAgeError as e:
        print(f"Invalid Age Error: {e}")

valid age25
valid age30
valid age40

In [25]:
validate_age(10)

valid age10

3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.

In [28]:
user_inputs = ['10', 'abc', '0', '5']

for user_input in user_inputs:
    try:
        number = int(user_input)
        result = 100 / number
        print(f"100 / {number} = {result}")

    except ZeroDivisionError:
        print("Cannot divide by zero")

    except ValueError:
        print(f"ValueError: '{user_input}' is not a valid number.")

    except Exception as e:
        print(f"Another exception: {e}")

100 / 10 = 10.0
ValueError: 'abc' is not a valid number.
Cannot divide by zero
100 / 5 = 20.0

Section B — NumPy
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.

In [29]:
import numpy as np

In [30]:
sample_array=np.array([])

In [31]:
sample_array=np.arange(1,21)

In [32]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
arry2=sample_array.reshape(4,5)

In [40]:
arry2.sum(axis=1)

array([15, 40, 65, 90])

In [41]:
arry2.sum(axis=0)

array([34, 38, 42, 46, 50])

In [42]:
greater=sample_array[sample_array>10]

In [43]:
greater

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
modified_arr = sample_array.copy()

In [46]:
modified_arr[modified_arr % 2 == 0] = -1

In [47]:
modified_arr

array([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1, 17,
       -1, 19, -1])

5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg

In [48]:
A = np.array([[1, 2], [3, 4]])

In [49]:
B = np.array([[5, 6], [7, 8]])

In [53]:
print(f"Additon{A+B}")

Additon[[ 6  8]
 [10 12]]

In [54]:
print(f"Substraction{A-B}")

Substraction[[-4 -4]
 [-4 -4]]

In [56]:
print(f"multiplication{A*B}")

multiplication[[ 5 12]
 [21 32]]

In [58]:
print(f"transpose of A{A.T}")

transpose of A[[1 3]
 [2 4]]

In [59]:
print("\nDeterminant of A:")
print(np.linalg.det(A))

Determinant of A:
-2.0000000000000004

In [60]:
print("\nInverse of A:")
print(np.linalg.inv(A))

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1

In [64]:
np.random.seed(42)
sample_array=np.random.randint(1,101,15)

In [66]:
sample_array.mean()

np.float64(58.06666666666667)

In [68]:
print("\nMean:", np.mean(sample_array))
print("Median:", np.median(sample_array))
print("Standard Deviation:", np.std(sample_array))
print("Minimum:", np.min(sample_array))
print("Maximum:", np.max(sample_array))

Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100

In [70]:
desc_arr = np.sort(sample_array)[::-1]

In [72]:
desc_arr

array([100,  93,  88,  87,  83,  75,  75,  72,  61,  52,  24,  22,  21,
        15,   3], dtype=int32)

In [74]:

top3_indices = np.argsort(sample_array)[-3:][::-1]

In [75]:
top3_indices

array([11,  1, 10])

In [78]:
normalized_arr = (sample_array - np.min(sample_array)) / (np.max(sample_array) - np.min(sample_array))

In [80]:
normalized_arr

array([0.50515464, 0.92783505, 0.12371134, 0.71134021, 0.59793814,
       0.18556701, 0.82474227, 0.86597938, 0.74226804, 0.74226804,
       0.87628866, 1.        , 0.21649485, 0.        , 0.19587629])

. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.

In [81]:
import pandas as pd

In [84]:
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

In [86]:
df=pd.DataFrame(data)

In [91]:
df[0:3]

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

In [92]:
df.dtypes

Name          object
Age            int64
Department    object
Score          int64
dtype: object

In [93]:
def get_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 75:
        return 'B'
    else:
        return 'C'

In [94]:
df["grade"]=df["Score"].apply(get_grade)

In [95]:
df

    Name  Age    Department  Score grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

In [96]:
sorted_df=df.sort_values(by="Score",ascending=False)

In [97]:
ai_df = df[df["Department"] == "AI"]

In [98]:
ai_df

    Name  Age Department  Score grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B

8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame.

In [99]:
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

In [100]:
avg_score = df.groupby("Department")["Score"].mean()

In [101]:
avg_score

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

In [102]:
highest_score_row = df.loc[df["Score"].idxmax()]

In [103]:
highest_score_row

Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

In [104]:
df.rename(columns={"Score": "Marks"}, inplace=True)

In [105]:
df

    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

In [106]:
df = df.drop("Age", axis=1)

In [107]:
df

    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67

9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.

In [14]:
import pandas as pd
import numpy as np

In [15]:
data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

In [16]:
df = pd.DataFrame(data)

In [17]:
print(df.isnull().sum())

Product    0
Price      2
Stock      1
dtype: int64

In [18]:
price_mean = df["Price"].mean()
df["Price"] = df["Price"].fillna(price_mean)

In [19]:
df = df.dropna(subset=["Stock"])

In [21]:
df.to_csv('cleaned_products.csv',index=False)

In [22]:
'''
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError)
''';

In [23]:
DataFrame=pd.read_csv('cleaned_products.csv')

In [25]:
DataFrame

     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2  Sharpener   8.000000   30.0
3      Ruler   7.666667   20.0

In [26]:
DataFrame.shape

(4, 3)

In [27]:
DataFrame.columns.tolist()

['Product', 'Price', 'Stock']

In [28]:
DataFrame['Total_Value'] = DataFrame['Price'] * DataFrame['Stock']

In [29]:
DataFrame

     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

In [30]:
DataFrame.describe()

           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000

In [31]:
try:
    Data=pd.read_csv('cleaned_products.csv')
    print("Successfullt Loaded")
    print(Data.head(3))
except:
    print("File does not exits")

Successfullt Loaded
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2  Sharpener   8.000000   30.0