In [1]:
# pandas

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\swara\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\swara\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\swara\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\swara\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\swara\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\swara\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#1d data structures in pandas

In [4]:
#Pandas Series

In [6]:
#Creating Panda Series

In [7]:
import pandas as pd

In [8]:
s=pd.Series([10,20,30])

In [11]:
s

0    10
1    20
2    30
dtype: int64

In [13]:
s=pd.Series([10,20,30],index=['a','b','c'])

In [14]:
s

a    10
b    20
c    30
dtype: int64

In [15]:
s=pd.Series(["swaraj",18,100],index=['name','age','marks'])

In [16]:
s

name     swaraj
age          18
marks       100
dtype: object

In [18]:
#From dictionary

In [19]:
data={"name":"Rahul","age":35,"marks":90}

In [21]:
s=pd.Series(data)

In [22]:
s

name     Rahul
age         35
marks       90
dtype: object

In [23]:
data={"subject":"python","age":35,"year":90,"marks":89}

In [24]:
s=pd.Series(data)

In [25]:
s

subject    python
age            35
year           90
marks          89
dtype: object

In [26]:
# from a single value

In [29]:
s=pd.Series(5,index=[0,1,2,3,45,5,4,])

In [30]:
s

0     5
1     5
2     5
3     5
45    5
5     5
4     5
dtype: int64

In [31]:
# Attributes

In [33]:
s=pd.Series([10,20,30],index=["a","b","c"])

In [34]:
s

a    10
b    20
c    30
dtype: int64

In [35]:
s.values

array([10, 20, 30])

In [36]:

s.index

Index(['a', 'b', 'c'], dtype='object')

In [37]:
s.dtype

dtype('int64')

In [38]:
s.shape

(3,)

In [39]:
# data manipulation

In [40]:
s=pd.Series([1,2,3])

In [42]:
s*3

0    3
1    6
2    9
dtype: int64

In [43]:
# Handling Missing Values

In [44]:
s=pd.Series([1,None,3])

In [45]:
s

0    1.0
1    NaN
2    3.0
dtype: float64

In [46]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [48]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [51]:
s.fillna(75)

0     1.0
1    75.0
2     3.0
dtype: float64

In [52]:
#indexing

In [53]:
s=pd.Series([10,20,30],index=["a","b","c"])

In [54]:
s

a    10
b    20
c    30
dtype: int64

In [55]:
s['a']

np.int64(10)

In [1]:
import pandas as pd

In [2]:
roll=pd.Series([1,2,3,4,5])
name=pd.Series(['sia','ravi','geet','ajeenkya','avinash'])
marks=pd.Series([85,67,59,40,90])

In [10]:
df=pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [11]:
df

   id      name  marks
0   1       sia     85
1   2      ravi     67
2   3      geet     59
3   4  ajeenkya     40
4   5   avinash     90

In [12]:
df.ndim

2

In [13]:
df.shape

(5, 3)

In [14]:
df.size

15

In [15]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [16]:
"""
url https://mitu.co.in/dataset will connect to drive folder

download all the datasets starting with student*
put them in the same file folder as ur current working directory
""";

In [11]:
import pandas as pd

In [12]:
df=pd.read_csv("student.csv")

In [13]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [14]:
df.shape

(10, 5)

In [15]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [16]:
df=pd.read_csv("student1.csv")

In [17]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [18]:
col=['roll','name','class','marks','age']

In [19]:
df=pd.read_csv("student1.csv",names=col)

In [20]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [21]:
# student3.tsv

In [39]:
df=pd.read_csv("student3.tsv",sep='\t')

In [40]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21