In [1]:
# student3.csv

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df=pd.read_csv("student.csv")

In [5]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [6]:
df.shape

(10, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [8]:
# fix structural errors

In [9]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5     ayesha
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [13]:
df['name']=df['name'].str.title()

In [15]:
df

   roll     name class  marks  age
0     1     Anil    TE  56.77   22
1     2     Amit    TE  59.77   21
2     3   Aniket    BE  76.88   19
3     4  Ajinkya    TE  69.66   20
4     5     Asha    TE  63.28   20
5     6   Ayesha    BE  49.55   20
6     7     Amar    BE  65.34   19
7     8    Amita    BE  68.33   23
8     9     Amol    TE  56.75   20
9    10    Anmol    BE  78.66   21

In [16]:
df['class']

0    TE
1    TE
2    BE
3    TE
4    TE
5    BE
6    BE
7    BE
8    TE
9    BE
Name: class, dtype: object

In [17]:
df=pd.read_csv('student3.csv')

In [18]:
df.shape

(16, 5)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [24]:
 df['marks ']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks , dtype: float64

In [26]:
df.columns=df.columns.str.strip()

In [27]:
df['marks']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [28]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [31]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [38]:
df.duplicated().sum()

np.int64(1)

In [42]:
df.drop_duplicates(inplace=True)

In [43]:
df

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28   NaN
5      6   ayesha    BE    NaN  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66   NaN
11    11   surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin   NaN  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [44]:
#missing values

In [45]:
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [46]:
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [47]:
# removing rows with null

In [48]:
df.dropna()

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
15    15  shalini    TE  63.45  20.0

In [49]:
# filling the missing values

In [50]:
df

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28   NaN
5      6   ayesha    BE    NaN  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66   NaN
11    11   surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin   NaN  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [52]:
df['marks'].fillna(45)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5     45.00
6     65.34
7     68.33
8     56.75
10    78.66
11    45.00
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [56]:
sf=df['marks'].mean

In [57]:
sf

<bound method Series.mean of 0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64>

In [58]:
df['marks'].fillna(df['marks'].mean())

0     56.770000
1     59.770000
2     76.880000
3     69.660000
4     63.280000
5     67.753077
6     65.340000
7     68.330000
8     56.750000
10    78.660000
11    67.753077
12    74.120000
13    88.450000
14    59.330000
15    63.450000
Name: marks, dtype: float64

In [60]:
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [61]:
df['class'].fillna(df['class'].mode())

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      be
8      TE
10     BE
11     TE
12     TE
13     be
14    NaN
15     TE
Name: class, dtype: object

In [62]:
df['class'].mode()

0    TE
Name: class, dtype: object

In [64]:
df['class'].fillna(df["class"].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     be
8     TE
10    BE
11    TE
12    TE
13    be
14    TE
15    TE
Name: class, dtype: object

In [65]:
df.ffill()

    roll     name class  marks   age
0      1     anil    TE  56.77  22.0
1      2     amit    TE  59.77  21.0
2      3   aniket    BE  76.88  19.0
3      4  ajinkya    TE  69.66  20.0
4      5     asha    TE  63.28  20.0
5      6   ayesha    BE  63.28  20.0
6      7     amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     amol    TE  56.75  20.0
10    10    anmol    BE  78.66  20.0
11    11   surbhi    TE  78.66  23.0
12    12    Sujay    TE  74.12  22.0
13    13  subhash    be  88.45  21.0
14    14   sachin    be  59.33  21.0
15    15  shalini    TE  63.45  20.0

In [68]:
df.bfill(inplace=True)

In [69]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64